//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.03 at 03:47:34 下午 CST 
//


package org.googlecode.perftrace.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.googlecode.perftrace.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.googlecode.perftrace.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PerftraceConfig.Matcher.RegexMatcher }
     * 
     */
    public PerftraceConfig.Matcher.RegexMatcher createPerftraceConfigMatcherRegexMatcher() {
        return new PerftraceConfig.Matcher.RegexMatcher();
    }

    /**
     * Create an instance of {@link PerftraceConfig.PatternConf.Pelement }
     * 
     */
    public PerftraceConfig.PatternConf.Pelement createPerftraceConfigPatternConfPelement() {
        return new PerftraceConfig.PatternConf.Pelement();
    }

    /**
     * Create an instance of {@link PerftraceConfig }
     * 
     */
    public PerftraceConfig createPerftraceConfig() {
        return new PerftraceConfig();
    }

    /**
     * Create an instance of {@link PerftraceConfig.PatternConf.Pelement.Patattr }
     * 
     */
    public PerftraceConfig.PatternConf.Pelement.Patattr createPerftraceConfigPatternConfPelementPatattr() {
        return new PerftraceConfig.PatternConf.Pelement.Patattr();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Matcher.AnnotationMatcher }
     * 
     */
    public PerftraceConfig.Matcher.AnnotationMatcher createPerftraceConfigMatcherAnnotationMatcher() {
        return new PerftraceConfig.Matcher.AnnotationMatcher();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Global.RootMethods.RootMethod.ParametersType.Type }
     * 
     */
    public PerftraceConfig.Global.RootMethods.RootMethod.ParametersType.Type createPerftraceConfigGlobalRootMethodsRootMethodParametersTypeType() {
        return new PerftraceConfig.Global.RootMethods.RootMethod.ParametersType.Type();
    }

    /**
     * Create an instance of {@link PerftraceConfig.PatternConf }
     * 
     */
    public PerftraceConfig.PatternConf createPerftraceConfigPatternConf() {
        return new PerftraceConfig.PatternConf();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Global.RootMethods.RootMethod.ParametersType }
     * 
     */
    public PerftraceConfig.Global.RootMethods.RootMethod.ParametersType createPerftraceConfigGlobalRootMethodsRootMethodParametersType() {
        return new PerftraceConfig.Global.RootMethods.RootMethod.ParametersType();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Matcher }
     * 
     */
    public PerftraceConfig.Matcher createPerftraceConfigMatcher() {
        return new PerftraceConfig.Matcher();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Matcher.NameMatcher }
     * 
     */
    public PerftraceConfig.Matcher.NameMatcher createPerftraceConfigMatcherNameMatcher() {
        return new PerftraceConfig.Matcher.NameMatcher();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Global }
     * 
     */
    public PerftraceConfig.Global createPerftraceConfigGlobal() {
        return new PerftraceConfig.Global();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Global.RootMethods }
     * 
     */
    public PerftraceConfig.Global.RootMethods createPerftraceConfigGlobalRootMethods() {
        return new PerftraceConfig.Global.RootMethods();
    }

    /**
     * Create an instance of {@link PerftraceConfig.Global.RootMethods.RootMethod }
     * 
     */
    public PerftraceConfig.Global.RootMethods.RootMethod createPerftraceConfigGlobalRootMethodsRootMethod() {
        return new PerftraceConfig.Global.RootMethods.RootMethod();
    }

    /**
     * Create an instance of {@link PerftraceConfig.PatternConf.Pelement.Profiled }
     * 
     */
    public PerftraceConfig.PatternConf.Pelement.Profiled createPerftraceConfigPatternConfPelementProfiled() {
        return new PerftraceConfig.PatternConf.Pelement.Profiled();
    }

}
