//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.03 at 03:47:34 下午 CST 
//


package org.googlecode.perftrace.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatternType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PatternType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="annotation"/>
 *     &lt;enumeration value="regex"/>
 *     &lt;enumeration value="name"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PatternType")
@XmlEnum
public enum PatternType {

    @XmlEnumValue("annotation")
    ANNOTATION("annotation"),
    @XmlEnumValue("regex")
    REGEX("regex"),
    @XmlEnumValue("name")
    NAME("name");
    private final String value;

    PatternType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PatternType fromValue(String v) {
        for (PatternType c: PatternType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
