//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.03 at 03:47:34 下午 CST 
//


package org.googlecode.perftrace.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patternConf" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pelement" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="profiled">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" default="@@USE_METHOD_NAME" />
 *                                     &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="logger" type="{http://www.w3.org/2001/XMLSchema}string" default="org.googlecode.perftrace.TimingLogger" />
 *                                     &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" default="INFO" />
 *                                     &lt;attribute name="logFailureSeparately" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                                     &lt;attribute name="timeThreshold" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *                                     &lt;attribute name="normalAndSlowSuffixesEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="patattr" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="type" type="{}PatternType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="global" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="timeThreshold" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="rootMethods" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="rootMethod" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="methodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="parametersType" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="type" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="maxWatchChainDepth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="maxAdditionMsgCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="logPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="matcher" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="annotationMatcher" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="annotationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="regexMatcher" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="patterns" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="excludePatterns" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="nameMatcher" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="mappedNames" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="EchoToken" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patternConf",
    "global",
    "matcher"
})
@XmlRootElement(name = "perftraceConfig")
public class PerftraceConfig {

    protected PerftraceConfig.PatternConf patternConf;
    protected PerftraceConfig.Global global;
    protected PerftraceConfig.Matcher matcher;
    @XmlAttribute(name = "EchoToken")
    protected String echoToken;
    @XmlAttribute(name = "TimeStamp")
    protected String timeStamp;
    @XmlAttribute(name = "Version")
    protected String version;
    @XmlAttribute(name = "Target")
    protected String target;

    /**
     * Gets the value of the patternConf property.
     * 
     * @return
     *     possible object is
     *     {@link PerftraceConfig.PatternConf }
     *     
     */
    public PerftraceConfig.PatternConf getPatternConf() {
        return patternConf;
    }

    /**
     * Sets the value of the patternConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerftraceConfig.PatternConf }
     *     
     */
    public void setPatternConf(PerftraceConfig.PatternConf value) {
        this.patternConf = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link PerftraceConfig.Global }
     *     
     */
    public PerftraceConfig.Global getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerftraceConfig.Global }
     *     
     */
    public void setGlobal(PerftraceConfig.Global value) {
        this.global = value;
    }

    /**
     * Gets the value of the matcher property.
     * 
     * @return
     *     possible object is
     *     {@link PerftraceConfig.Matcher }
     *     
     */
    public PerftraceConfig.Matcher getMatcher() {
        return matcher;
    }

    /**
     * Sets the value of the matcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerftraceConfig.Matcher }
     *     
     */
    public void setMatcher(PerftraceConfig.Matcher value) {
        this.matcher = value;
    }

    /**
     * Gets the value of the echoToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEchoToken() {
        return echoToken;
    }

    /**
     * Sets the value of the echoToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEchoToken(String value) {
        this.echoToken = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="timeThreshold" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="rootMethods" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="rootMethod" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="methodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="parametersType" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="type" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="maxWatchChainDepth" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="maxAdditionMsgCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="logPattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timeThreshold",
        "rootMethods",
        "maxWatchChainDepth",
        "maxAdditionMsgCount",
        "logPattern"
    })
    public static class Global {

        @XmlElement(defaultValue = "0")
        protected Long timeThreshold;
        protected PerftraceConfig.Global.RootMethods rootMethods;
        @XmlElement(defaultValue = "2000")
        protected int maxWatchChainDepth;
        @XmlElement(defaultValue = "20")
        protected int maxAdditionMsgCount;
        @XmlElement(required = true, defaultValue = "plain")
        protected String logPattern;

        /**
         * Gets the value of the timeThreshold property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTimeThreshold() {
            return timeThreshold;
        }

        /**
         * Sets the value of the timeThreshold property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTimeThreshold(Long value) {
            this.timeThreshold = value;
        }

        /**
         * Gets the value of the rootMethods property.
         * 
         * @return
         *     possible object is
         *     {@link PerftraceConfig.Global.RootMethods }
         *     
         */
        public PerftraceConfig.Global.RootMethods getRootMethods() {
            return rootMethods;
        }

        /**
         * Sets the value of the rootMethods property.
         * 
         * @param value
         *     allowed object is
         *     {@link PerftraceConfig.Global.RootMethods }
         *     
         */
        public void setRootMethods(PerftraceConfig.Global.RootMethods value) {
            this.rootMethods = value;
        }

        /**
         * Gets the value of the maxWatchChainDepth property.
         * 
         */
        public int getMaxWatchChainDepth() {
        	if(maxWatchChainDepth == 0)
        		this.maxWatchChainDepth = 2000;
            return maxWatchChainDepth;
        }

        /**
         * Sets the value of the maxWatchChainDepth property.
         * 
         */
        public void setMaxWatchChainDepth(int value) {
            this.maxWatchChainDepth = value;
        }

        /**
         * Gets the value of the maxAdditionMsgCount property.
         * 
         */
        public int getMaxAdditionMsgCount() {
        	if(maxAdditionMsgCount == 0)
        		maxAdditionMsgCount = 20;
            return maxAdditionMsgCount;
        }

        /**
         * Sets the value of the maxAdditionMsgCount property.
         * 
         */
        public void setMaxAdditionMsgCount(int value) {
            this.maxAdditionMsgCount = value;
        }

        /**
         * Gets the value of the logPattern property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogPattern() {
            return logPattern;
        }

        /**
         * Sets the value of the logPattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogPattern(String value) {
            this.logPattern = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="rootMethod" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="methodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="parametersType" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="type" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rootMethod"
        })
        public static class RootMethods {

            @XmlElement(required = true)
            protected List<PerftraceConfig.Global.RootMethods.RootMethod> rootMethod;

            /**
             * Gets the value of the rootMethod property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the rootMethod property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRootMethod().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PerftraceConfig.Global.RootMethods.RootMethod }
             * 
             * 
             */
            public List<PerftraceConfig.Global.RootMethods.RootMethod> getRootMethod() {
                if (rootMethod == null) {
                    rootMethod = new ArrayList<PerftraceConfig.Global.RootMethods.RootMethod>();
                }
                return this.rootMethod;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="methodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="parametersType" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="type" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "methodName",
                "parametersType"
            })
            public static class RootMethod {

                @XmlElement(required = true)
                protected String methodName;
                protected PerftraceConfig.Global.RootMethods.RootMethod.ParametersType parametersType;

                /**
                 * Gets the value of the methodName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMethodName() {
                    return methodName;
                }

                /**
                 * Sets the value of the methodName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMethodName(String value) {
                    this.methodName = value;
                }

                /**
                 * Gets the value of the parametersType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PerftraceConfig.Global.RootMethods.RootMethod.ParametersType }
                 *     
                 */
                public PerftraceConfig.Global.RootMethods.RootMethod.ParametersType getParametersType() {
                    return parametersType;
                }

                /**
                 * Sets the value of the parametersType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PerftraceConfig.Global.RootMethods.RootMethod.ParametersType }
                 *     
                 */
                public void setParametersType(PerftraceConfig.Global.RootMethods.RootMethod.ParametersType value) {
                    this.parametersType = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="type" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "type"
                })
                public static class ParametersType {

                    @XmlElement(required = true)
                    protected List<PerftraceConfig.Global.RootMethods.RootMethod.ParametersType.Type> type;

                    /**
                     * Gets the value of the type property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the type property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getType().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link PerftraceConfig.Global.RootMethods.RootMethod.ParametersType.Type }
                     * 
                     * 
                     */
                    public List<PerftraceConfig.Global.RootMethods.RootMethod.ParametersType.Type> getType() {
                        if (type == null) {
                            type = new ArrayList<PerftraceConfig.Global.RootMethods.RootMethod.ParametersType.Type>();
                        }
                        return this.type;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Type {

                        @XmlAttribute(name = "class")
                        @XmlSchemaType(name = "anySimpleType")
                        protected String clazz;

                        /**
                         * Gets the value of the clazz property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getClazz() {
                            return clazz;
                        }

                        /**
                         * Sets the value of the clazz property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setClazz(String value) {
                            this.clazz = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="annotationMatcher" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="annotationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="regexMatcher" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="patterns" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="excludePatterns" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="nameMatcher" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="mappedNames" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "annotationMatcher",
        "regexMatcher",
        "nameMatcher"
    })
    public static class Matcher {

        protected PerftraceConfig.Matcher.AnnotationMatcher annotationMatcher;
        protected PerftraceConfig.Matcher.RegexMatcher regexMatcher;
        protected PerftraceConfig.Matcher.NameMatcher nameMatcher;

        /**
         * Gets the value of the annotationMatcher property.
         * 
         * @return
         *     possible object is
         *     {@link PerftraceConfig.Matcher.AnnotationMatcher }
         *     
         */
        public PerftraceConfig.Matcher.AnnotationMatcher getAnnotationMatcher() {
            return annotationMatcher;
        }

        /**
         * Sets the value of the annotationMatcher property.
         * 
         * @param value
         *     allowed object is
         *     {@link PerftraceConfig.Matcher.AnnotationMatcher }
         *     
         */
        public void setAnnotationMatcher(PerftraceConfig.Matcher.AnnotationMatcher value) {
            this.annotationMatcher = value;
        }

        /**
         * Gets the value of the regexMatcher property.
         * 
         * @return
         *     possible object is
         *     {@link PerftraceConfig.Matcher.RegexMatcher }
         *     
         */
        public PerftraceConfig.Matcher.RegexMatcher getRegexMatcher() {
            return regexMatcher;
        }

        /**
         * Sets the value of the regexMatcher property.
         * 
         * @param value
         *     allowed object is
         *     {@link PerftraceConfig.Matcher.RegexMatcher }
         *     
         */
        public void setRegexMatcher(PerftraceConfig.Matcher.RegexMatcher value) {
            this.regexMatcher = value;
        }

        /**
         * Gets the value of the nameMatcher property.
         * 
         * @return
         *     possible object is
         *     {@link PerftraceConfig.Matcher.NameMatcher }
         *     
         */
        public PerftraceConfig.Matcher.NameMatcher getNameMatcher() {
            return nameMatcher;
        }

        /**
         * Sets the value of the nameMatcher property.
         * 
         * @param value
         *     allowed object is
         *     {@link PerftraceConfig.Matcher.NameMatcher }
         *     
         */
        public void setNameMatcher(PerftraceConfig.Matcher.NameMatcher value) {
            this.nameMatcher = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="annotationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "annotationType"
        })
        public static class AnnotationMatcher {

            @XmlElement(required = true)
            protected String annotationType;

            /**
             * Gets the value of the annotationType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnnotationType() {
                return annotationType;
            }

            /**
             * Sets the value of the annotationType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnnotationType(String value) {
                this.annotationType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="mappedNames" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mappedNames"
        })
        public static class NameMatcher {

            @XmlElement(required = true)
            protected String mappedNames;

            /**
             * Gets the value of the mappedNames property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMappedNames() {
                return mappedNames;
            }

            /**
             * Sets the value of the mappedNames property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMappedNames(String value) {
                this.mappedNames = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="patterns" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="excludePatterns" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "patterns",
            "excludePatterns"
        })
        public static class RegexMatcher {

            @XmlElement(required = true)
            protected String patterns;
            @XmlElement(required = true)
            protected String excludePatterns;

            /**
             * Gets the value of the patterns property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPatterns() {
                return patterns;
            }

            /**
             * Sets the value of the patterns property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPatterns(String value) {
                this.patterns = value;
            }

            /**
             * Gets the value of the excludePatterns property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExcludePatterns() {
                return excludePatterns;
            }

            /**
             * Sets the value of the excludePatterns property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExcludePatterns(String value) {
                this.excludePatterns = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pelement" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="profiled">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" default="@@USE_METHOD_NAME" />
     *                           &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="logger" type="{http://www.w3.org/2001/XMLSchema}string" default="org.googlecode.perftrace.TimingLogger" />
     *                           &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" default="INFO" />
     *                           &lt;attribute name="logFailureSeparately" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *                           &lt;attribute name="timeThreshold" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
     *                           &lt;attribute name="normalAndSlowSuffixesEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="patattr" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="type" type="{}PatternType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pelement"
    })
    public static class PatternConf {

        @XmlElement(required = true)
        protected List<PerftraceConfig.PatternConf.Pelement> pelement;

        /**
         * Gets the value of the pelement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pelement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPelement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PerftraceConfig.PatternConf.Pelement }
         * 
         * 
         */
        public List<PerftraceConfig.PatternConf.Pelement> getPelement() {
            if (pelement == null) {
                pelement = new ArrayList<PerftraceConfig.PatternConf.Pelement>();
            }
            return this.pelement;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="profiled">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" default="@@USE_METHOD_NAME" />
         *                 &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="logger" type="{http://www.w3.org/2001/XMLSchema}string" default="org.googlecode.perftrace.TimingLogger" />
         *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" default="INFO" />
         *                 &lt;attribute name="logFailureSeparately" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *                 &lt;attribute name="timeThreshold" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
         *                 &lt;attribute name="normalAndSlowSuffixesEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="patattr" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="type" type="{}PatternType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "profiled",
            "patattr"
        })
        public static class Pelement {

            @XmlElement(required = true)
            protected PerftraceConfig.PatternConf.Pelement.Profiled profiled;
            @XmlElement(required = true)
            protected List<PerftraceConfig.PatternConf.Pelement.Patattr> patattr;

            /**
             * Gets the value of the profiled property.
             * 
             * @return
             *     possible object is
             *     {@link PerftraceConfig.PatternConf.Pelement.Profiled }
             *     
             */
            public PerftraceConfig.PatternConf.Pelement.Profiled getProfiled() {
                return profiled;
            }

            /**
             * Sets the value of the profiled property.
             * 
             * @param value
             *     allowed object is
             *     {@link PerftraceConfig.PatternConf.Pelement.Profiled }
             *     
             */
            public void setProfiled(PerftraceConfig.PatternConf.Pelement.Profiled value) {
                this.profiled = value;
            }

            /**
             * Gets the value of the patattr property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the patattr property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPatattr().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PerftraceConfig.PatternConf.Pelement.Patattr }
             * 
             * 
             */
            public List<PerftraceConfig.PatternConf.Pelement.Patattr> getPatattr() {
                if (patattr == null) {
                    patattr = new ArrayList<PerftraceConfig.PatternConf.Pelement.Patattr>();
                }
                return this.patattr;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="type" type="{}PatternType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Patattr {

                @XmlValue
                protected String value;
                @XmlAttribute
                protected PatternType type;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PatternType }
                 *     
                 */
                public PatternType getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PatternType }
                 *     
                 */
                public void setType(PatternType value) {
                    this.type = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="tag" type="{http://www.w3.org/2001/XMLSchema}string" default="@@USE_METHOD_NAME" />
             *       &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="logger" type="{http://www.w3.org/2001/XMLSchema}string" default="org.googlecode.perftrace.TimingLogger" />
             *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" default="INFO" />
             *       &lt;attribute name="logFailureSeparately" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
             *       &lt;attribute name="timeThreshold" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
             *       &lt;attribute name="normalAndSlowSuffixesEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Profiled {

                @XmlAttribute
                protected String tag;
                @XmlAttribute
                protected String message;
                @XmlAttribute
                protected String logger;
                @XmlAttribute
                protected String level;
                @XmlAttribute
                protected Boolean logFailureSeparately;
                @XmlAttribute
                protected Long timeThreshold;
                @XmlAttribute
                protected Boolean normalAndSlowSuffixesEnabled;

                /**
                 * Gets the value of the tag property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTag() {
                    if (tag == null) {
                        return "@@USE_METHOD_NAME";
                    } else {
                        return tag;
                    }
                }

                /**
                 * Sets the value of the tag property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTag(String value) {
                    this.tag = value;
                }

                /**
                 * Gets the value of the message property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMessage() {
                    return message;
                }

                /**
                 * Sets the value of the message property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMessage(String value) {
                    this.message = value;
                }

                /**
                 * Gets the value of the logger property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLogger() {
                    if (logger == null) {
                        return "org.googlecode.perftrace.TimingLogger";
                    } else {
                        return logger;
                    }
                }

                /**
                 * Sets the value of the logger property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLogger(String value) {
                    this.logger = value;
                }

                /**
                 * Gets the value of the level property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLevel() {
                    if (level == null) {
                        return "INFO";
                    } else {
                        return level;
                    }
                }

                /**
                 * Sets the value of the level property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLevel(String value) {
                    this.level = value;
                }

                /**
                 * Gets the value of the logFailureSeparately property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isLogFailureSeparately() {
                    if (logFailureSeparately == null) {
                        return true;
                    } else {
                        return logFailureSeparately;
                    }
                }

                /**
                 * Sets the value of the logFailureSeparately property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setLogFailureSeparately(Boolean value) {
                    this.logFailureSeparately = value;
                }

                /**
                 * Gets the value of the timeThreshold property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *     
                 */
                public long getTimeThreshold() {
                    if (timeThreshold == null) {
                        return  0L;
                    } else {
                        return timeThreshold;
                    }
                }

                /**
                 * Sets the value of the timeThreshold property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *     
                 */
                public void setTimeThreshold(Long value) {
                    this.timeThreshold = value;
                }

                /**
                 * Gets the value of the normalAndSlowSuffixesEnabled property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isNormalAndSlowSuffixesEnabled() {
                    if (normalAndSlowSuffixesEnabled == null) {
                        return true;
                    } else {
                        return normalAndSlowSuffixesEnabled;
                    }
                }

                /**
                 * Sets the value of the normalAndSlowSuffixesEnabled property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setNormalAndSlowSuffixesEnabled(Boolean value) {
                    this.normalAndSlowSuffixesEnabled = value;
                }

            }

        }

    }

}
